version: '3'
services:
  student_service:
    image: amicopo/uva_devops_wk1:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
    - .:/usr/src/app:r
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"
