name: Builb Test and push
on: [push]
env:
  IMAGE_NAME: uva_devops_wk1
  REPO_NAME: amicopo


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME
    - name: run docker
      run: |
        docker run -d -p 27017:27017 -host=172.17.0.2  mongo:4 && \
        docker run -d -p 8080:8080 -host=172.17.0.2 --env MONGO_URI=mongodb://172.17.0.2:27017 $REPO_NAME/$IMAGE_NAME:latest && \
          docker ps && sleep 5
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: |
          docker push $REPO_NAME/$IMAGE_NAME
